### ISSUE TITLE
Include Indicators

### ISSUE THREAD

**Issue by IgorJakovljevic** [crypto-com/crypto-exchange#4]
More of a feature request. 

Would it be possible to include indicators in the "/v1/ticker" request

So an additional parameter indicator_list=['MACD', '%R'], or something of this sort. This would be quite useful.

**Comment by mortyspace** [comment]
This will be cpu costly to calculate on server, you can download data and process this for example by ta-lib [https://github.com/mrjbq7/ta-lib](https://github.com/mrjbq7/ta-lib)

**Comment by IgorJakovljevic** [comment]
@mortyspace jap you are right, found the library a week ago but did not have time to implement it. Thanks
